### ISSUE TITLE
Extension error just after instalation in fedora 32

### ISSUE THREAD

**Issue by nmendozam** [Rafostar/cast-to-tv-desktop-addon#10]
Hello,

I have installed the extension from extensions.gnome.org in  Fedora 32  with Gnome 3.36.5, but immediately after the installation an error message appear in the gnome-extensions page.

I checked the log and It shows the below error, I haven't been able to find out how to install this module.
```
ImportError: No JS module 'addons' found in search path
```
Also, the description says that I must press an "Install npm modules" button but don't see the Cast Settings anywhere.

Let me know if you need any other info.

**Comment by Rafostar** [comment]
This is an add-on for Cast to TV extension. You have to install [Cast to TV](https://extensions.gnome.org/extension/1544/cast-to-tv) first.
