### ISSUE TITLE
Error loading the extension GNOME Shell 3.36.4

### ISSUE THREAD

**Issue by bastien-wink** [Rafostar/cast-to-tv-desktop-addon#12]
I followed installation steps for ubuntu, it's loaded in gnome-tweaks then this warning is displayed `Error loading the extension`

![image](https://user-images.githubusercontent.com/7903123/101912363-ee705c00-3bc1-11eb-9ef5-0eab88808a5b.png)

Where can be found the error log ?

I am using
GNOME Shell 3.36.4
Ubuntu 20.04.1 LTS

**Comment by Rafostar** [comment]
GNOME extensions log errors to `journalctl`.

**Comment by Rafostar** [comment]
But even without doing that I can already tell you what the problem is :smile: 

This is an add-on for GNOME `Cast to TV` extension (it only extends its functionality by adding desktop streaming). You need to have installed and working Cast to TV extension first.

**Comment by bastien-wink** [comment]
Great ! It fixed the issue
