### ISSUE TITLE
Cast desktop is not an option

### ISSUE THREAD

**Issue by pauzzz** [Rafostar/cast-to-tv-desktop-addon#15]
Hi, I'm on gnome-shell 3.28.4, I've installed the cast-to-tv extension using the `pre-3.36` branch as indicated and the npm modules are installed as indicated through cast settings > modules > install npm modules. Both extensions are enabled and I've restarted gnome-shell with no luck on the `desktop` option. Everything else works though.

**Comment by Rafostar** [comment]
@pauzzz 

Extension was made much earlier then desktop add-on so it has older versions that work with older GNOME Shell. Desktop add-on was made later and the earliest version it works with is 3.34.

BTW: Also does not work on 3.38+ currently. This complete lack on API stability in GNOME is killing me.

**Comment by pauzzz** [comment]
Gotcha, working now on ubuntu 20.04. I'm also curious if there's work being done on extending the desktop instead of mirroring but seems like a very big feature add.
