### ISSUE TITLE
Transcoding not working

### ISSUE THREAD

**Issue by ComanSoftware** [Rafostar/cast-to-tv-desktop-addon#16]
I don't get any errors when debugging but i get a notification that says: Could not start desktop recording

**Comment by Rafostar** [comment]
Install gstreamer and its plugins, mainly:

```sh
apt install gstreamer1.0-libav
apt install gstreamer1.0-plugins-bad
```

Set "Audio encoder" to "AVENC AAC" in extension desktop preferences and retry casting desktop.

**Comment by ComanSoftware** [comment]
Thank you very much! Setting to AVENC AAC seems to solve it. 
But it still doesn't work because i wanted to cast it to a firetv stick using the App AirScreen.
Is there a way to make it work?

**Comment by Rafostar** [comment]
Only Google Cast protocol is supported. Extension was only tested with original Google Chromecast.
