### ISSUE TITLE
No menu entry for casting desktop

### ISSUE THREAD

**Issue by todoneunl** [Rafostar/cast-to-tv-desktop-addon#2]
First a lot of thanks for this extension! It works great!

I followed all the steps in the README, incl. installing all gstreamer-plugins and I'm running Xorg. It successfully install all modules and the desktop addon settings are displayed in the Cast to TV settings. Still there is no menu entry for desktop casting. I restarted the Gnome extension and I even logged out and in. What am I doing wrong?

Gnome 3.34.1 on Ubuntu 19.10

**Comment by Rafostar** [comment]
@jeroenpraat 
Did you remember to enable desktop addon in Gnome Tweaks afterwards?
There were few updates to the main extension since I last worked on desktop streaming part. Probably you are not doing anything wrong, desktop streaming has quite a few bugs and needs more optimisations anyway. I will try to finish this during my free time (by the end of this year).

**Comment by TheAifam5** [comment]
I don't see the option too. Installed `cast-to-tv` then followed the steps from this repo. I see the tab `Add-ons` and `Desktop`, but there is no menu entry like @jeroenpraat said.

**Comment by Rafostar** [comment]
I am working on desktop streaming right now. To improve it few changes to the main extension were needed so from now on it will only work with latest `cast to tv` git master (I updated the readme). I am doing some testing on my side and it is already usable (unlike google own in Chrome, my implementation works with audio and gives better video quality and smoother fps).

When I finish improving it I will look into this missing entry issue. @TheAifam5 What is your Gnome shell version?

**Comment by TheAifam5** [comment]
`GNOME Shell 3.34.1`

**Comment by Eeems** [comment]
@Rafostar Any news? I'm also unable to get a menu entry in GNOME Shell 3.34.2

**Comment by Rafostar** [comment]
@Eeems 
Latest so called "stable" GJS + GNOME versions have a bug that causes random shell crashes during cast. I informed GNOME devs about it and they agreed with me, that it is indeed their bug, but they do not know what causes it yet. In the meantime I decided to redo the communication between Node and Gnome in extension to work around it (and make it snappier). It takes priority now, after that I will have to implement the same new communications methods in add-ons to make them work again with next extension version.

**Comment by Rafostar** [comment]
I tried it on Ubuntu 19.10 Live ISO, but cannot reproduce this bug using latest git of both main extension and this addon. Maybe it was fixed somewhere along the way.

Can someone do a clean reinstall of both extensions from git, relogin/reboot, enable them in "Gnome Tweaks" and verify???

**Comment by Rafostar** [comment]
@Eeems @TheAifam5 @jeroenpraat 
Using latest GIT master versions of both main extension and desktop streaming addon, missing menu entry problem should now be resolved.

The addon still needs some optimization, but it is now working correctly on GNOME 3.34+ with Wayland or Xorg session and audio works too (at least on my end :smile: ). Clone both, install and enable in GNOME Tweaks and it should appear in Cast to TV menu.
