### ISSUE TITLE
Desktop Streaming Performance

### ISSUE THREAD

**Issue by andrew-wja** [Rafostar/cast-to-tv-desktop-addon#4]
The performance of the desktop stream is a little laggy over a gigabit ethernet connection!

I presume this is more to do with the efficiency of the gstreamer pipeline than the network link speed :)

**Comment by andrew-wja** [comment]
I have both AMD and NVIDIA gpu machines available so I can test both VAAPI and NVENC encoding if that would help!

**Comment by Rafostar** [comment]
Hi,
Today I pushed remaining changes to Cast to TV extension git and some improvements to desktop streaming with added missing options to its preferences. It now has option to enable or disable streaming with HLS and hardware acceleration.

I have not tested **hw encoding** due to lack of supporting hardware. It would be great if you could update both main extension and this addon and test if it works and if it does compare video quality and delays using combinations of different accelerations + enabled/disabled HLS. Also sharing some basic info about your used hardware (CPU model, GPU and Display resolution) would be great.

When comparing overall "smoothness" do not look at the mouse cursor movement (GNOME Shell draws it in a laggy way), but look for everything else like dragging windows, videos, animations etc.

Sorry to trouble you.

**Edit:** vaapi also requires `gstreamer-vaapi` package.

**Comment by andrew-wja** [comment]
Hi,
I installed gstreamer-vaapi, and updated the main extension and this addon. 

Streaming is very smooth and clean even without any hardware acceleration. I ran glxgears, played some video in VLC etc. However, there is a very long lag (roughly 3 seconds) between doing anything (maximize a window, move a window etc) and seeing the action happen on the remote display. There's no stuttering or tearing, the image quality is very good, but the input lag is still gigantic. Even mouse movement is smooth and clean, it just happens 2-3 seconds after I actually move the mouse :)

Unfortunately, if I turn on the hardware acceleration option (either NVENC or VAAPI, both with and without HLS), I see the same message: could not start desktop recording.

Here's the log on the AMD GPU machine:

```
Apr 15 16:03:33 AMDEEZUS-II dbus-daemon[5528]: [session uid=1000 pid=5528] Activating service name='org.gnome.Extensions' requested by ':1.15' (uid=1000 pid=5973 comm="/usr/bin/gnome-shell ")
Apr 15 16:03:33 AMDEEZUS-II dbus-daemon[5528]: [session uid=1000 pid=5528] Activating service name='org.gnome.Shell.Extensions' requested by ':1.113' (uid=1000 pid=7406 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Exte")
Apr 15 16:03:45 AMDEEZUS-II gnome-shell[5973]: ShellRecorder: failed to parse pipeline: no element "vaapih264enc"
Apr 15 16:03:45 AMDEEZUS-II gnome-shell[5973]: Cast to TV - Desktop Addon: Could not start desktop recording
```

and here from the NVIDIA one:
```
Apr 15 16:03:54 AMDEEZUS-II dbus-daemon[5528]: [session uid=1000 pid=5528] Activating service name='org.gnome.Extensions' requested by ':1.15' (uid=1000 pid=5973 comm="/usr/bin/gnome-shell ")
Apr 15 16:03:54 AMDEEZUS-II dbus-daemon[5528]: [session uid=1000 pid=5528] Activating service name='org.gnome.Shell.Extensions' requested by ':1.118' (uid=1000 pid=7472 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Exte")
Apr 15 16:04:11 AMDEEZUS-II gnome-shell[5973]: ShellRecorder: failed to parse pipeline: no element "nvh264enc"
Apr 15 16:04:11 AMDEEZUS-II gnome-shell[5973]: Cast to TV - Desktop Addon: Could not start desktop recording
```

**Comment by andrew-wja** [comment]
Actually, I think something is wrong with my installation of `gstreamer-vaapi`, because if I run this test command, I see the same error message

```
gst-launch-1.0 -ev videotestsrc num-buffers=60 ! timeoverlay ! vaapih264enc ! h264parse ! mp4mux ! filesink location=test.mp4
```

```
WARNING: erroneous pipeline: no element "vaapih264enc"
```

I'll check what's up with that AUR package

**Comment by Rafostar** [comment]
It seems to complain that both vaapi and nvidia plugins are not installed. I am not on Arch, so I do not know what is needed to get them recognized by gstreamer. If you have them installed you should be able to see their info using `gst-inspect-1.0`.
```
gst-inspect-1.0 vaapih264enc
```

**Comment by andrew-wja** [comment]
> Actually, I think something is wrong with my installation of `gstreamer-vaapi`, because if I run this test command, I see the same error message
> 
> ```
> gst-launch-1.0 -ev videotestsrc num-buffers=60 ! timeoverlay ! vaapih264enc ! h264parse ! mp4mux ! filesink location=test.mp4
> ```
> 
> ```
> WARNING: erroneous pipeline: no element "vaapih264enc"
> ```
> 
> I'll check what's up with that AUR package

This seems to fix the error for me: https://github.com/intel/media-driver/issues/114

However, the pipeline just sits there and doesn't actually do anything. 60 buffers should be 2 seconds worth of video, but the pipeline just hangs forever...

**Comment by andrew-wja** [comment]
> It seems to complain that both vaapi and nvidia plugins are not installed. I am not on Arch, so I do not know what is needed to get them recognized by gstreamer. If you have them installed you should be able to see their info using `gst-inspect-1.0`.
> 
> ```
> gst-inspect-1.0 vaapih264enc
> ```

With `gst-inspect-1.0 vaapih264enc`
```
No such element or plugin 'vaapih264enc'
```

With `GST_VAAPI_ALL_DRIVERS=1 gst-inspect-1.0 vaapih264enc` it looks good:

```
Factory Details:
  Rank                     primary (256)
  Long-name                VA-API H264 encoder
  Klass                    Codec/Encoder/Video/Hardware
  Description              A VA-API based H264 video encoder
  Author                   Wind Yuan <feng.yuan@intel.com>

Plugin Details:
  Name                     vaapi
  Description              VA-API based elements
  Filename                 /usr/lib/gstreamer-1.0/libgstvaapi.so
  Version                  1.16.2
  License                  LGPL
  Source module            gstreamer-vaapi
  Binary package           gstreamer-vaapi
  Origin URL               http://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstVideoEncoder
                         +----GstVaapiEncode
                               +----GstVaapiEncodeH264

Implemented Interfaces:
  GstPreset

Pad Templates:
  SRC template: 'src'
    Availability: Always
    Capabilities:
      video/x-h264
          stream-format: { (string)avc, (string)byte-stream }
              alignment: au
                profile: { (string)constrained-baseline, (string)baseline, (string)main, (string)high, (string)multiview-high, (string)stereo-high }
  
  SINK template: 'sink'
    Availability: Always
    Capabilities:
      video/x-raw(memory:VASurface)
                 format: { (string)ENCODED, (string)NV12, (string)I420, (string)YV12, (string)YUY2, (string)UYVY, (string)Y210, (string)P010_10LE, (string)AYUV, (string)Y410 }
                  width: [ 1, 2147483647 ]
                 height: [ 1, 2147483647 ]
              framerate: [ 0/1, 2147483647/1 ]
         interlace-mode: progressive
      video/x-raw
                 format: { (string)I420, (string)YV12, (string)YUY2, (string)UYVY, (string)AYUV, (string)VUYA, (string)RGBx, (string)BGRx, (string)xRGB, (string)xBGR, (string)RGBA, (string)BGRA, (string)ARGB, (string)ABGR, (string)RGB, (string)BGR, (string)Y41B, (string)Y42B, (string)YVYU, (string)Y444, (string)v210, (string)v216, (string)Y210, (string)Y410, (string)NV12, (string)NV21, (string)GRAY8, (string)GRAY16_BE, (string)GRAY16_LE, (string)v308, (string)RGB16, (string)BGR16, (string)RGB15, (string)BGR15, (string)UYVP, (string)A420, (string)RGB8P, (string)YUV9, (string)YVU9, (string)IYU1, (string)ARGB64, (string)AYUV64, (string)r210, (string)I420_10BE, (string)I420_10LE, (string)I422_10BE, (string)I422_10LE, (string)Y444_10BE, (string)Y444_10LE, (string)GBR, (string)GBR_10BE, (string)GBR_10LE, (string)NV16, (string)NV24, (string)NV12_64Z32, (string)A420_10BE, (string)A420_10LE, (string)A422_10BE, (string)A422_10LE, (string)A444_10BE, (string)A444_10LE, (string)NV61, (string)P010_10BE, (string)P010_10LE, (string)IYU2, (string)VYUY, (string)GBRA, (string)GBRA_10BE, (string)GBRA_10LE, (string)BGR10A2_LE, (string)GBR_12BE, (string)GBR_12LE, (string)GBRA_12BE, (string)GBRA_12LE, (string)I420_12BE, (string)I420_12LE, (string)I422_12BE, (string)I422_12LE, (string)Y444_12BE, (string)Y444_12LE, (string)GRAY10_LE32, (string)NV12_10LE32, (string)NV16_10LE32, (string)NV12_10LE40 }
                  width: [ 1, 2147483647 ]
                 height: [ 1, 2147483647 ]
              framerate: [ 0/1, 2147483647/1 ]
         interlace-mode: progressive

Element has no clocking capabilities.
Element has no URI handling capabilities.

Pads:
  SINK: 'sink'
    Pad Template: 'sink'
  SRC: 'src'
    Pad Template: 'src'

Element Properties:
  aud                 : Use AU (Access Unit) delimeter
                        flags: readable, writable
                        Boolean. Default: false
  bitrate             : The desired bitrate expressed in kbps (0: auto-calculate)
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 102400 Default: 0 
  cabac               : Enable CABAC entropy coding mode
                        flags: readable, writable
                        Boolean. Default: false
  compliance-mode     : Tune Encode quality/performance by relaxing specification compliance restrictions
                        flags: readable, writable
                        Enum "GstVaapiEncoderH264ComplianceMode" Default: 0, "strict"
                           (0): strict           - Strict compliance to the H264 Specification 
                           (1): restrict-buf-alloc - Restrict the allocation size of coded-buffer
  cpb-length          : Length of the CPB buffer in milliseconds
                        flags: readable, writable
                        Unsigned Integer. Range: 1 - 10000 Default: 1500 
  dct8x8              : Enable adaptive use of 8x8 transforms in I-frames
                        flags: readable, writable
                        Boolean. Default: false
  default-roi-delta-qp: The default delta-qp to apply to each Region of Interest(lower value means higher-quality, higher value means lower-quality)
                        flags: readable, writable
                        Integer. Range: -10 - 10 Default: -10 
  init-qp             : Initial quantizer value
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 51 Default: 26 
  keyframe-period     : Maximal distance between two keyframes (0: auto-calculate)
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 30 
  max-bframes         : Number of B-frames between I and P
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 10 Default: 0 
  mbbrc               : Macroblock level Bitrate Control
                        flags: readable, writable
                        Enum "GstVaapiEncoderMbbrc" Default: 0, "auto"
                           (0): auto             - Auto
                           (1): on               - On
                           (2): off              - Off
  min-qp              : Minimum quantizer value
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 51 Default: 1 
  name                : The name of the object
                        flags: readable, writable
                        String. Default: "vaapiencodeh264-0"
  num-slices          : Number of slices per frame
                        flags: readable, writable
                        Unsigned Integer. Range: 1 - 200 Default: 1 
  num-views           : Number of Views for MVC encoding
                        flags: readable, writable
                        Unsigned Integer. Range: 1 - 10 Default: 1 
  parent              : The parent of the object
                        flags: readable, writable
                        Object of type "GstObject"
  prediction-type     : Reference Picture Selection Modes
                        flags: readable, writable
                        Enum "GstVaapiEncoderH264PredictionType" Default: 0, "default"
                           (0): default          - Default encode, prev/next frame as ref 
                           (1): hierarchical-p   - Hierarchical P frame encode
                           (2): hierarchical-b   - Hierarchical B frame encode
  qos                 : Handle Quality-of-Service events from downstream
                        flags: readable, writable
                        Boolean. Default: false
  qp-ib               : Difference of QP between I and B frame (available only on CQP)
                        flags: readable, writable
                        Integer. Range: -51 - 51 Default: 0 
  qp-ip               : Difference of QP between I and P frame (available only on CQP)
                        flags: readable, writable
                        Integer. Range: -51 - 51 Default: 0 
  quality-level       : Encoding Quality Level (lower value means higher-quality/slow-encode,  higher value means lower-quality/fast-encode)
                        flags: readable, writable
                        Unsigned Integer. Range: 1 - 7 Default: 4 
  rate-control        : Rate control mode
                        flags: readable, writable
                        Enum "GstVaapiRateControlH264" Default: 1, "cqp"
                           (1): cqp              - Constant QP
                           (2): cbr              - Constant bitrate
                           (4): vbr              - Variable bitrate
                           (5): vbr_constrained  - Variable bitrate - Constrained
  refs                : Number of reference frames
                        flags: readable, writable
                        Unsigned Integer. Range: 1 - 8 Default: 1 
  temporal-levels     : Number of temporal levels in the encoded stream 
                        flags: readable, writable
                        Unsigned Integer. Range: 1 - 4 Default: 1 
  tune                : Encoder tuning option
                        flags: readable, writable
                        Enum "GstVaapiEncoderTuneH264" Default: 0, "none"
                           (0): none             - None
                           (1): high-compression - High compression
                           (3): low-power        - Low power mode
  view-ids            : Set of View Ids used for MVC encoding
                        flags: readable, writable
                        GstValueArray of GValues of type "guint"
```

**Comment by andrew-wja** [comment]
Hmm, this is quite odd. At least, it's required to set LIBVA_DRIVER_NAME correctly (or VDPAU_DRIVER if using VDPAU).

`$ LIBVA_DRIVER_NAME=radeonsi vainfo `

```
vainfo: VA-API version: 1.7 (libva 2.7.1)
vainfo: Driver version: Mesa Gallium driver 20.0.4 for AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.6.4-arch1-1, LLVM 9.0.1)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```

However, this doesn't seem to be working for gstreamer:
`$ LIBVA_DRIVER_NAME=radeonsi gst-inspect-1.0 vaapih264enc`

```
No such element or plugin 'vaapih264enc'
```

But if I use `GST_VAAPI_ALL_DRIVERS=1` it works. It looks like gstreamer is only capable of using a fallback driver, instead of the actual `radeonsi` driver. I suspect the same thing will happen on the NVIDIA machine. I'll have a look on the gstreamer project and see if this behaviour is known.

`

**Comment by andrew-wja** [comment]
According to the documentation (https://gstreamer.freedesktop.org/documentation/vaapi/index.html?gi-language=c) that is supposed to work!

**Comment by andrew-wja** [comment]
> According to the documentation (https://gstreamer.freedesktop.org/documentation/vaapi/index.html?gi-language=c) that is supposed to work!

OK, so it is a known bug: https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/issues/194

Since it is marked as fixed, I presume the fix has just not made it to the distro packages yet. However, I ran the debug command `GST_DEBUG=*vaapi*:6 gst-inspect-1.0 vaapih264enc` and I can see that it is, in fact, selecting the correct driver (`radeonsi`). I'll export GST_VAAPI_ALL_DRIVERS=1 in my bashrc and see if casting works after that.

**Comment by andrew-wja** [comment]
OK, some progress: now, with the right environment variables set, I can use gstreamer from the command line.

```
$ env | egrep "DRIVER|GST"
VDPAU_DRIVER=radeonsi
LIBVA_DRIVER_NAME=radeonsi
GST_VAAPI_ALL_DRIVERS=1
```

However, I still see the same error message from the extension. From the context of code running in a shell extension, is the user environment visible? I presume that gstreamer is just using the standard `getenv()` C function, so that seems like maybe the user environment is not visible inside the extension, or perhaps I need to export those variables somewhere else, if my .bashrc is run after the shell starts...

**Comment by andrew-wja** [comment]
Ah, GNOME devs strike again: https://unix.stackexchange.com/questions/317282/set-environment-variables-for-gnome-on-wayland-and-bash-on-virtual-terminals-or

**Comment by andrew-wja** [comment]
So, the reason the mesa driver is blacklisted in gstreamer is because there really are bugs :sweat_smile: 

I set these variables in `/etc/environment` and logged out and in again

```
LIBVA_DRIVER_NAME=radeonsi
VDPAU_DRIVER=radeonsi
GST_VAAPI_ALL_DRIVERS=1
```

Now, if I turn on hardware acceleration, my video card driver crashes as soon as I try to cast the desktop, and I have to reboot the machine. There is a bug with fullstream video in the drivers, which is why gstreamer has blacklisted them. That's why the simple 2 second video pipeline is hanging also, but since that runs in a terminal, I can kill the terminal. Unfortunately when the hang happens in the shell extension, I can't even Ctrl-Alt-F{2,3,4} to get to a tty :(

I will try on the NVIDIA machine, over there `/etc/environment` needs to have

```
LIBVA_DRIVER_NAME=vdpau
VDPAU_DRIVER=nvidia
GST_VAAPI_ALL_DRIVERS=1
```
The environment variable configuration could probably go in the README? Just so future users don't need to go looking for how to set up hardware acceleration from scratch.

**Comment by andrew-wja** [comment]
Hmm.

So, on NVIDIA, it doesn't work at all. I can run the NVENC and NVDEC test programs here: https://medium.com/@multi.flexi/how-to-get-info-about-nvdec-and-nvenc-capabilities-of-your-gpu-6ecc9a5d4dac

However, both NVENC and VAAPI options seem to be broken on NVIDIA.

To use VAAPI on NVIDIA, you have to use the vdpau "backend", which is then implemented in the driver. Unfortunately, this seems to be non-functional via gstreamer. I can see the VAAPI capabilities of my GPU with vainfo, but gstreamer does not load the vaapi component. `gst-inspect-1.0 vaapi` says `No such element or plugin 'vaapi'`

With NVENC, the situation is the same: according to the gstreamer project, there is an nvenc/nvdec module (in gst-plugins-bad) https://gstreamer.freedesktop.org/documentation/nvdec/index.html?gi-language=c

However, this also results in `No such element or plugin` if I try to inspect it in gstreamer. I looked at all the shared libraries in the package, and actually there is no .so for nvenc or nvdec. This *could* be because the arch linux package for gst-plugins-bad does not build the nvenc or nvdec compoents, but I don't see why they would disable them. I will check if they do though! If it turns out that they have those plugins disabled, it is probably because there are bugs, like in mesa for AMD cards.

The only remaining option is to use the hardware encoder on the Intel iGPU. I *think* I have access to a machine that has one of those, I will check :)

I think you can probably close this issue, because it's not this project's problem if gstreamer doesn't work for one reason or another :D 

Thanks for adding the encoder selection regardless! If things get fixed upstream, at least it will begin working here as well without you having to do any more work (as long as they don't change the APIs... >_>)

**Comment by Rafostar** [comment]
Thank you very much for testing.

VAAPI on NVIDIA is not supported anyway, so I added their proprietary NVENC encoding support.

As for 3-4 sec delay... This is the lowest I was able to get on Chromecast. It seems that Default Media Receiver app that Google allows free usage for software developers to use is set by them to always cache 3 secs ahead and do not have any option to disable/reduce it further. Seems like other apps that tried to achieve desktop streaming have the same problem. For example `mkchromecast`:
[https://github.com/muammar/mkchromecast/issues/104](https://github.com/muammar/mkchromecast/issues/104)

At least I was able to match others in performance and they do not have hardware accel too. My implementation using GNOME Shell Recorder works on Wayland in contrast to others (even Google Chrome browser does not work on Wayland yet).

**Comment by Rafostar** [comment]
@andrew-wja 
I am not an Nvidia expert either, but I think that `vdpau` that you tried to use and `nvenc` are two different standards (nvenc is Nvidia proprietary and requires binary video drivers).

It seems that Arch build has disabled `nvenc`:
[https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gst-plugins-bad](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gst-plugins-bad)

Anyway, thanks again for testing I will update readme with your findings.

**Comment by andrew-wja** [comment]
> @andrew-wja
> I am not an Nvidia expert either, but I think that `vdpau` that you tried to use and `nvenc` are two different standards (nvenc is Nvidia proprietary and requires binary video drivers).
> 
> It seems that Arch build has disabled `nvenc`:
> https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gst-plugins-bad
> 
> Anyway, thanks again for testing I will update readme with your findings.

Yes, the situation on nvidia is very strange.. To use vaapi, you use a library that implements vaapi using vdpau! There is a huge thread on the nvidia dev forums about vdpau, but it seems like nvidia are not updating their vdpau implementation any more, so NVENC/NVDEC are really the only supported acceleration interfaces on new nvidia cards.

I'll build the package with nvenc enabled and see if it works.

**Comment by Rafostar** [comment]
@andrew-wja 
BTW. You said earlier (before installing missing gstreamer plugins) that recording fails to start and gives you only a notification that it failed without any info why. So here is what GNOME devs have to say about it :smile: 

> There is no way currently to get details on how recording failed to start.

I found it when I was hacking recorder code.
Source: [https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/src/shell-recorder.c#L1519](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/src/shell-recorder.c#L1519)

**Comment by andrew-wja** [comment]
I created a package for the gstreamer NVENC and NVDEC plugins (https://aur.archlinux.org/packages/?O=0&K=gstreamer-nvidia)

However, it seems like the NVENC and NVDEC support in gstreamer has not had a maintainer in more than a year, and it won't build against CUDA 10.2, so it's possible that it has bitrotted! I'll see if they want to update it, or failing that, if I can at least make a user patch to include in the Arch package that gets things running.

**Comment by Rafostar** [comment]
OK. Since streaming seems to work smooth on software encoding when CPU is powerful enough and not working hardware acceleration is a GStreamer issue. I will close this for now.

I would like to reduce delay, but this would require writing a custom receiver app (app that runs on Chromecast device) besides the extension which is a sender app. Unfortunately maintaining the extension alone gives me more than enough trouble as it constantly needs to be fixed for each new GNOME Shell release...
