### ISSUE TITLE
Add voaacenc as alternative to faac/fdkaac

### ISSUE THREAD

**Issue by logix2** [Rafostar/cast-to-tv-desktop-addon#5]
Ubuntu doesn't enable faac/fdkaac in Gstreamer. With all the possible GStreamer plugins installed, I get:
```
$ gst-inspect-1.0 fdkaac
No such element or plugin 'fdkaac'

$ gst-inspect-1.0 faac
No such element or plugin 'faac'
```
And I can't stream my desktop with audio.

I couldn't find any official info on this unfortunately. Only some users here who also noticed it's not enabled: [https://ubuntuforums.org/showthread.php?t=2404956](https://ubuntuforums.org/showthread.php?t=2404956)

But anyway, I really wanted to get this to work, so I edited the extension source and added [voaacenc](https://gstreamer.freedesktop.org/documentation/voaacenc/index.html?gi-language=c) (it's part of gstreamer1.0-plugins-bad) as an alternative to faac/fdkaacenc, and everything seems to be working well (tested with a Chromecast Ultra). So maybe you can enable this too?

This is what I did:

```
--- pipe.js
+++ pipe.js
@@ -83,6 +83,12 @@
 					'tns=true'
 				);
 				break;
+			case 'voaacenc':
+				pipe.push(
+					'voaacenc', // gst-plugins-bad
+					'hard-resync=true'
+				);
+				break;				
 			default:
 				pipe.push(
 					'fdkaacenc', // gst-plugins-bad
```
and
```
--- desktop_prefs.js
+++ desktop_prefs.js
@@ -78,6 +78,7 @@
 		widget = new Gtk.ComboBoxText({halign:Gtk.Align.END});
 		widget.append('fdkaacenc', "FDK AAC");
 		widget.append('faac', "FAAC");
+		widget.append('voaacenc', "VO-AACENC");		
 		Settings.bind('encoder', widget, 'active-id', Gio.SettingsBindFlags.DEFAULT);
 		addToGrid(this, label, widget);
 
```

I can create a pull request if you wish.

**Comment by Rafostar** [comment]
I though fdkaac and faac were the only commonly used encoders. Thanks for investigating.
> I can create a pull request if you wish.

Sure, a PR is welcome.

**Comment by logix2** [comment]
There's also [avenc_aac](https://gstreamer.freedesktop.org/documentation/libav/avenc_aac.html?gi-language=c) as an alternative (part of gstreamer1.0-libav on Ubuntu). I'm not sure how to test which one is better :) This one seems to be working fine too.

Which one would you prefer? Or both? I'll make a pull request after that.

**Comment by Rafostar** [comment]
If i remember correctly ffmpeg-libav plugins (like avenc_aac) were obsoleted. If voaacenc is working correctly it should be preferred. It also comes as part of gstreamer bad plugins and does not require gstreamer ffmpeg bindings to be installed.

**Comment by Rafostar** [comment]
@logix2 
I did some reading on the net and it seems that voaacenc is really old (last version from 2013). And according to FFmpeg docs [here](https://trac.ffmpeg.org/wiki/Encode/AAC) FDK is highest quality (default on Fedora) while native aac is second best (I think that native one is the libav plugin you found earlier - avenc_aac). So it might be worth including too. Weird that Ubuntu is lacking the other two plugins...

Let me know if you can add it to your PR too. If it is too much trouble I will do it. Really sorry to trouble you.

**Comment by logix2** [comment]
I'll add avenc_aac too. No trouble at all!

**Comment by Rafostar** [comment]
Thanks. I think it should be called `Libav AAC` in widget.

**Comment by logix2** [comment]
Despite the package being called libav, it's using FFmpeg now, not libav (I guess it used to use Libav in the past). So I'm not sure if that's the correct way to call it. See here (scroll to the actual packages and see the description): https://launchpad.net/ubuntu/+source/gst-libav1.0/1.16.2-2 

And here https://gstreamer.freedesktop.org/documentation/libav/avenc_aac.html?gi-language=c it's says it's part of "Package – GStreamer FFMPEG Plug-ins git"

So maybe call it "Libav/FFmpeg AAC"?

**Comment by Rafostar** [comment]
Lets leave it as `AVENC AAC` like you called it. It makes it clear what is the name of required GStreamer codec.

**Comment by Rafostar** [comment]
Merged. Thank you.
