### ISSUE TITLE
Desktop casting fails

### ISSUE THREAD

**Issue by hendersj** [Rafostar/cast-to-tv-desktop-addon#9]
Running on openSUSE Leap 15.2.

Casting images and video to my Chromecast ultra works fine, but when I try to start desktop casting, I see the following logged messages in the system log:

```
Jul 21 10:03:27 artifactovol.fbnet.hendersj.net gnome-shell[6332]: Error in recording pipeline: Can not initialize x264 encoder.
Jul 21 10:03:27 artifactovol.fbnet.hendersj.net gnome-shell[6332]: recorder_record_frame: assertion 'recorder->current_pipeline != NULL' failed
Jul 21 10:03:27 artifactovol.fbnet.hendersj.net gnome-shell[6332]: g_file_new_for_path: assertion 'path != NULL' failed
Jul 21 10:03:27 artifactovol.fbnet.hendersj.net gnome-shell[6332]: g_file_get_uri: assertion 'G_IS_FILE (file)' failed
Jul 21 10:03:27 artifactovol.fbnet.hendersj.net gnome-shell[6332]: gtk_recent_manager_add_item: assertion 'uri != NULL' failed
Jul 21 10:03:27 artifactovol.fbnet.hendersj.net gnome-shell[6332]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

For openSUSE, I had to install the gstreamer-plugins-ugly-orig-addon package to get the x264 encoder library.

The video driver in use is the radeon driver (lspci reports the card as `01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Curacao PRO [Radeon R7 370 / R9 270/370 OEM]` if that makes a difference).

What additional info is needed to troubleshoot this issue?

**Comment by Rafostar** [comment]
What is your computer screen resolution?

**Comment by hendersj** [comment]
Thanks for the follow-up!  I'm running a dual-monitor configuration; the primary monitor is running at 2560x1440, the secondary at 1280x1024.

**Comment by Rafostar** [comment]
I haven't tested video scaling on above Full HD (or multi-monitors). Could you temporarily enable/connect only single screen and set desktop resolution to 1920x1080 and check if this will allow you to cast without those errors?

**Comment by hendersj** [comment]
Just gave that a shot - disabled the second monitor in display preferences, set resolution for the primary to 1920x1080, restarted the cast server, and attempted to connect.

Log output was unchanged.

Anything else I can try?  Happy to experiment to help out.

**Comment by Rafostar** [comment]
GNOME Shell unfortunately doesn't have debugging of the built-in screen recorder that is giving you errors, but there is a test script inside this repo that uses the same codecs (including h264enc). The script creates a test video instead of actually recording screen. Maybe try cloning this repo somewhere and running `test.js` inside test folder. It can be run as follows:
```
gjs ./test.js "alsa_output.pci-0000_00_1b.0.hdmi-stereo.monitor" "fdkaacenc"
```
Replace the `fdkaacenc` with the name of the GStreamer encoder you set in extension prefs and alsa device with the audio device you got from:
```
pacmd list-sources | grep "name:"
```

Try to see if it actually runs the recording or exits with similiar error like before.

**Comment by hendersj** [comment]
Thanks.  I've just had a chance to try this out, but I can't get a successful test.

When I run `pacmd list-sources | grep "name:"`, I get the following output:

```
	name: <alsa_output.pci-0000_01_00.1.hdmi-stereo.monitor>
	name: <alsa_output.pci-0000_00_1b.0.analog-stereo.monitor>
	name: <bluez_sink.08_EB_ED_82_BE_2A.a2dp_sink.monitor>
	name: <alsa_output.usb-Astro_Gaming_Astro_MixAmp_Pro-00.analog-stereo.monitor>
	name: <alsa_input.usb-Astro_Gaming_Astro_MixAmp_Pro-00.mono-fallback>
```

Then I run the test.js script, and no matter what I put as the second parameter (here it is with avencaacenc as the value, but I've tried others with the same result), I get the following result:

```
$ gjs ./test.js "alsa_output.pci-0000_01_00.1.hdmi-stereo.monitor" "avencaacenc"
Gjs-Message: 14:54:51.450: JS LOG: CURRENT GSTREAMER PIPE: videotestsrc ! video/x-raw,format=I420,width=320,height=240,framerate=15/1 ! videorate skip-to-first=true ! video/x-raw,framerate=30/1 ! x264enc threads=2 tune=zerolatency cabac=true sliced-threads=true b-adapt=false rc-lookahead=0 key-int-max=30 speed-preset=superfast bitrate=2000 ! video/x-h264,profile=main ! mqueue.sink_0 pulsesrc device=alsa_output.pci-0000_01_00.1.hdmi-stereo.monitor provide-clock=true do-timestamp=true buffer-time=40000 ! queue leaky=2 max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! audiorate skip-to-first=true ! audio/x-raw,channels=2 ! fdkaacenc hard-resync=true ! multiqueue name=mqueue ! aparse. mqueue.src_1 ! vparse. mqueue.src_0 ! h264parse name=vparse config-interval=-1 ! outmux. aacparse name=aparse ! matroskamux name=outmux min-cluster-duration=0 ! tcpserversink host=127.0.0.1 port=4007 sync=false sync-method=burst-keyframe burst-format=default recover-policy=latest time-min=-1 blocksize=64 buffers-max=1 burst-value=1000 max-lateness=1 timeout=10000000000 units-max=64 units-soft-max=64
Gjs-Message: 14:54:51.450: JS LOG: PERFORMING RECORDING TEST...
WARNING: erroneous pipeline: no element "fdkaacenc"
```

I'm configured to use `AVENC AAC` in the extension prefs.

I'm sure this is just user error on my part.  :)

**Comment by Rafostar** [comment]
The correct audio encoder name in your case would be: `avenc_aac`.

**Comment by hendersj** [comment]
Perfect, thanks - definitely user error on my part for that. :)

Here's the output:

```
$ gjs ./test.js "alsa_output.pci-0000_01_00.1.hdmi-stereo.monitor" "avenc_aac"
Gjs-Message: 13:05:02.584: JS LOG: CURRENT GSTREAMER PIPE: videotestsrc ! video/x-raw,format=I420,width=320,height=240,framerate=15/1 ! videorate skip-to-first=true ! video/x-raw,framerate=30/1 ! x264enc threads=2 tune=zerolatency cabac=true sliced-threads=true b-adapt=false rc-lookahead=0 key-int-max=30 speed-preset=superfast bitrate=2000 ! video/x-h264,profile=main ! mqueue.sink_0 pulsesrc device=alsa_output.pci-0000_01_00.1.hdmi-stereo.monitor provide-clock=true do-timestamp=true buffer-time=40000 ! queue leaky=2 max-size-buffers=0 max-size-time=0 max-size-bytes=0 ! audiorate skip-to-first=true ! audio/x-raw,channels=2 ! avenc_aac hard-resync=true ! multiqueue name=mqueue ! aparse. mqueue.src_1 ! vparse. mqueue.src_0 ! h264parse name=vparse config-interval=-1 ! outmux. aacparse name=aparse ! matroskamux name=outmux min-cluster-duration=0 ! tcpserversink host=127.0.0.1 port=4007 sync=false sync-method=burst-keyframe burst-format=default recover-policy=latest time-min=-1 blocksize=64 buffers-max=1 burst-value=1000 max-lateness=1 timeout=10000000000 units-max=64 units-soft-max=64
Gjs-Message: 13:05:02.585: JS LOG: PERFORMING RECORDING TEST...
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Redistribute latency...
Setting pipeline to PLAYING ...
New clock: GstPulseSrcClock
Redistribute latency...
```

Note that this is running with the dual monitor setup - if it is more helpful for me to switch to the lower resolution and disable the second display, let me know.

**Comment by Rafostar** [comment]
The recording test in your output was successful, so the codecs do work. I have seen similar problems with GNOME screen recorder in multimonitor configurations. Maybe setting single monitor 1920x1080 and then login out and back in (with still single screen enabled at login) would help? This is just a guess, through. The errors you have in system log are not very informative and using the same codecs from command line do work. Unless GNOME developers implement proper debugging of their screen recorder, we cannot do much.

**Comment by hendersj** [comment]
Interestingly, I just tried again, and I'm seeing both screens now, scaled, in the configuration they are in on my desktop (See attached photo).

![20200806_185045](https://user-images.githubusercontent.com/2662071/89600344-ab1e6f00-d816-11ea-9a6b-4f3abeb4198f.jpg)

Not sure what changed, but this seems to be working correctly now.

**Comment by Rafostar** [comment]
> Not sure what changed, but this seems to be working correctly now.

Looks like it does. There is already a separate issue with request to be able to select streamed screen instead of both. So I am closing this one.
